### ISSUE TITLE
There is a part which is not multilingual.

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#13]
I got a screen copy of the part not multilingualized.
English language files and Japanese language files have the same number of lines.
And all Japanese language files are converted to Japanese and English is not left.

![2017-07-16 22 39 23](https://user-images.githubusercontent.com/1645189/28248167-ee37f048-6a7a-11e7-8b63-bbc07d94e1f7.png)

![2017-07-16 22 40 50](https://user-images.githubusercontent.com/1645189/28248172-f73e3440-6a7a-11e7-9337-9b6f9c418193.png)

![2017-07-16 22 42 37](https://user-images.githubusercontent.com/1645189/28248222-d93c2cd0-6a7b-11e7-89db-8c79beb3a5b5.png)

If possible, I would like you to display it in local time.
![2017-07-16 22 43 27](https://user-images.githubusercontent.com/1645189/28248177-0cb8fac6-6a7b-11e7-99d7-f25b155cede5.png)

![2017-07-16 22 44 07](https://user-images.githubusercontent.com/1645189/28248178-159f917c-6a7b-11e7-8959-b3909728ab44.png)

![2017-07-16 22 45 41](https://user-images.githubusercontent.com/1645189/28248208-847c4fe0-6a7b-11e7-8ef1-85536ecceb7a.png)

![2017-07-16 22 48 18](https://user-images.githubusercontent.com/1645189/28248210-8bfd94fe-6a7b-11e7-87f5-70ec5255b2e0.png)

**Comment by dgarcia360** [comment]
Hi @mizunashi,

Thanks for reporting the issue.

I have been working on translating all the controllers during last week. However, I had to add more strings to translate to each i18n file, which are the following:

  "LOGOUT": "Log out",
  "CREATE_ACCOUNT": "Create Account",
  "IMPORT_ACCOUNT": "Import Account",
  "SIMPLE_WALLET_WARNING": "We are not responsible for any loss that could be due to the entropy of key generation.",
  "NOTHING_TO_SHOW": "Nothing to show",
  "PRIVATE_KEY_WALLET_WARNING": "Private key wallets use ONLY a password to encrypt the imported private key. Therefore it's crucial to select a SAFE password.",
  "IMPORT_ACCOUNT_QR_WARNING": "To use QR wallet scanner, you must use the same password as your current wallet account",
  "NOTHING_TO_SHOW": "Nothing to show",
  "DATE": "Date",
  "ALERT_ADDRESS_COPIED": "Transaction address has been copied",

It will be great if you could do a pull request in order to update Japanese language 😄 

Regarding  display time in local time, I'm very attached to NEMSDK at the moment, but I'll figure out how to do it. I suggest you open a new issue in order to solve it.

**Comment by mizunashi** [comment]
I think that it was seriously tough. Thank you very much.
The words that Japanese people seem to understand are "OK" and "Cancel", so I asked for such a request.

Currently this is AM 6: 00, but I work on all night with other urgent debugging work.
I think that I would like to work as soon as possible, but please let me sleep ...

I think that it is necessary to put the concept of the time zone in NEMSDK, so I will request it here.

I'm really thankful to you.
